# infrastructure/.github/workflows/deploy-infrastructure.yml
name: Deploy Infrastructure

on:
  push:
    branches: [
      main,
      add-bot-platmform
    ]
    paths:
      - 'shared/**'
      - 'api-server/terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.TERRAFORM_ROLE_ARN }}
        aws-region: ${{ secrets.AWS_REGION }}
        role-duration-seconds: 1200

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Terraform Init
      working-directory: shared/terraform
      run: terraform init

    - name: Terraform Plan
      working-directory: shared/terraform
      env:
        TF_VAR_allowed_ip: ${{ secrets.ALLOWED_IP }}
        TF_VAR_environment: ${{ secrets.ENVIRONMENT }}
      run: terraform plan -out=tfplan
    
    - name: Terraform Apply
      working-directory: shared/terraform
      run: terraform apply tfplan